### ISSUE TITLE
Figure out branch naming scheme

### ISSUE THREAD

**Issue by Tencona** [turris-games/Valkyrie#24]
Needs to be able to handle multiple issues being solved at once, as well as a summary of what's happened

`12-16-fixed-things` is awful.

`12-16_fixed-things` is slightly better?
`12_16-fixed_things`?

**Comment by Tencona** [comment]
I believe # can be used in branch names. I only made a branch. I need to see if it can go through a PR.

`#12-#16_fixed-stuff`?

**Comment by clee-dev** [comment]
I vote `#12-#16_fixed-stuff`

**Comment by Tencona** [comment]
`#<issue number>_<hyphenated-description>`
`#24_deciding-on-branch-naming-scheme`
`#12-#16_fixed-stuff`

The vote is unanimous. 
Closing issue.
